version: '3.8'

services:
  auth_api:
    build:
      context: ./../auth_api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./../auth_api:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - shared_network

  auth_service:
    build:
      context: ./../auth_service
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./../auth_service:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - shared_network

  auth_app:
    build:
      context: ./../auth_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge